package bean;
// Generated 02/10/2023 15:05:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PedidoFgv generated by hbm2java
 */
@Entity
@Table(name="pedido_fgv"
    ,catalog="db_felipe_ronceti"
)
public class PedidoFgv  implements java.io.Serializable {


     private int idpedidoFgv;
     private String nomeclienteFgv;
     private String enderecoentregaFgv;
     private String modelotelefoneFgv;
     private Date dataentregaFgv;
     private BigDecimal valorpedidoFgv;

    public PedidoFgv() {
    }

    public PedidoFgv(int idpedidoFgv, String nomeclienteFgv, String enderecoentregaFgv, String modelotelefoneFgv, Date dataentregaFgv, BigDecimal valorpedidoFgv) {
       this.idpedidoFgv = idpedidoFgv;
       this.nomeclienteFgv = nomeclienteFgv;
       this.enderecoentregaFgv = enderecoentregaFgv;
       this.modelotelefoneFgv = modelotelefoneFgv;
       this.dataentregaFgv = dataentregaFgv;
       this.valorpedidoFgv = valorpedidoFgv;
    }
   
     @Id 

    
    @Column(name="idpedido_fgv", unique=true, nullable=false)
    public int getIdpedidoFgv() {
        return this.idpedidoFgv;
    }
    
    public void setIdpedidoFgv(int idpedidoFgv) {
        this.idpedidoFgv = idpedidoFgv;
    }

    
    @Column(name="nomecliente_fgv", nullable=false, length=20)
    public String getNomeclienteFgv() {
        return this.nomeclienteFgv;
    }
    
    public void setNomeclienteFgv(String nomeclienteFgv) {
        this.nomeclienteFgv = nomeclienteFgv;
    }

    
    @Column(name="enderecoentrega_fgv", nullable=false, length=45)
    public String getEnderecoentregaFgv() {
        return this.enderecoentregaFgv;
    }
    
    public void setEnderecoentregaFgv(String enderecoentregaFgv) {
        this.enderecoentregaFgv = enderecoentregaFgv;
    }

    
    @Column(name="modelotelefone_fgv", nullable=false, length=45)
    public String getModelotelefoneFgv() {
        return this.modelotelefoneFgv;
    }
    
    public void setModelotelefoneFgv(String modelotelefoneFgv) {
        this.modelotelefoneFgv = modelotelefoneFgv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataentrega_fgv", nullable=false, length=10)
    public Date getDataentregaFgv() {
        return this.dataentregaFgv;
    }
    
    public void setDataentregaFgv(Date dataentregaFgv) {
        this.dataentregaFgv = dataentregaFgv;
    }

    
    @Column(name="valorpedido_fgv", nullable=false, precision=10)
    public BigDecimal getValorpedidoFgv() {
        return this.valorpedidoFgv;
    }
    
    public void setValorpedidoFgv(BigDecimal valorpedidoFgv) {
        this.valorpedidoFgv = valorpedidoFgv;
    }




}


